const colors = {
  light: {
    // ── Golden Era palette ──────────────────────────────────────────────────
    // Warm amber-honey tones; every surface feels bathed in golden-hour light.
    text: '#2D1800',
    tint: '#E07800',
    background: '#FFF8EE',
    foreground: '#2D1800',
    card: '#FFFFFF',
    cardForeground: '#2D1800',
    primary: '#E07800',
    primaryForeground: '#FFFFFF',
    // Gradient pair for scan button, hero banners, active pills
    primaryGradientStart: '#FFC84A',
    primaryGradientEnd: '#E07800',
    secondary: '#FFF0D0',
    secondaryForeground: '#5C3A00',
    muted: '#FFF0D0',
    mutedForeground: '#B08040',
    accent: '#3A5FA0',
    accentForeground: '#FFFFFF',
    destructive: '#D9463E',
    destructiveForeground: '#FFFFFF',
    border: '#F0E0C0',
    input: '#F0E0C0',
    // Semantic status colours
    owned: '#2D9E6B',
    wanted: '#D97832',
    forTrade: '#5B6EE8',
    gold: '#E07800',
    // ── Sea Glass Home semantic palette (scoped to Home) ───────────────────
    homeBackground: '#E8F7F3',
    homeSurface: '#F9FFFC',
    homeInk: '#123F47',
    homeMuted: '#58777A',
    homeLine: '#C8E4DF',
    homeAqua: '#D9F1EC',
    homeCoral: '#E86D61',
    homeCoralDeep: '#A83F3D',
    homeSand: '#D9AF66',
    homeSandInk: '#84601F',
    homeTeal: '#16525A',
    homeTealSoft: '#3C7778',
    homeWarmSurface: '#FFF8E9',
    homeWarmLine: '#E5C985',
    homeHeroText: '#FFFDF5',
    homeHeroMuted: '#FFF2D7',
    homeHeroSubtitle: '#FFF6E8',
    homeCollectText: '#F3FFFA',
    homeShadow: '#8A4C49',
  },
  dark: {
    text: '#EDE8DF',
    tint: '#D4AC54',
    background: '#0E0E1A',
    foreground: '#EDE8DF',
    card: '#1A1A2E',
    cardForeground: '#EDE8DF',
    primary: '#D4AC54',
    primaryForeground: '#0E0E1A',
    primaryGradientStart: '#D4AC54',
    primaryGradientEnd: '#A87730',
    secondary: '#222236',
    secondaryForeground: '#EDE8DF',
    muted: '#222236',
    mutedForeground: '#9494A8',
    accent: '#5B80D4',
    accentForeground: '#FFFFFF',
    destructive: '#D9463E',
    destructiveForeground: '#FFFFFF',
    border: '#2A2A40',
    input: '#2A2A40',
    // Semantic status colours (same in both schemes)
    owned: '#2D9E6B',
    wanted: '#D97832',
    forTrade: '#5B6EE8',
    gold: '#D4AC54',
    // ── Sea Glass Home semantic palette (scoped to Home) ───────────────────
    homeBackground: '#102A2E',
    homeSurface: '#18383B',
    homeInk: '#E3F4EF',
    homeMuted: '#A3C3BD',
    homeLine: '#31585A',
    homeAqua: '#214A4B',
    homeCoral: '#F08A7D',
    homeCoralDeep: '#FFAAA0',
    homeSand: '#E2BC76',
    homeSandInk: '#F0CF8E',
    homeTeal: '#0B454A',
    homeTealSoft: '#397479',
    homeWarmSurface: '#3E3624',
    homeWarmLine: '#75613A',
    homeHeroText: '#FFFDF5',
    homeHeroMuted: '#FFF2D7',
    homeHeroSubtitle: '#FFF6E8',
    homeCollectText: '#F3FFFA',
    homeShadow: '#000000',
  },
  radius: 16,
};

export default colors;
