const colors = {
  light: {
    text: '#1C1C2E',
    tint: '#C4933A',
    background: '#F5F2ED',
    foreground: '#1C1C2E',
    card: '#FFFFFF',
    cardForeground: '#1C1C2E',
    primary: '#C4933A',
    primaryForeground: '#FFFFFF',
    secondary: '#EDE8DF',
    secondaryForeground: '#1C1C2E',
    muted: '#EDE8DF',
    mutedForeground: '#7A7A8C',
    accent: '#3A5FA0',
    accentForeground: '#FFFFFF',
    destructive: '#D9463E',
    destructiveForeground: '#FFFFFF',
    border: '#DDD7CD',
    input: '#DDD7CD',
    // Semantic status colours
    owned: '#2D9E6B',
    wanted: '#D97832',
    forTrade: '#5B6EE8',
    gold: '#C4933A',
  },
  dark: {
    text: '#EDE8DF',
    tint: '#D4AC54',
    background: '#0E0E1A',
    foreground: '#EDE8DF',
    card: '#1A1A2E',
    cardForeground: '#EDE8DF',
    primary: '#D4AC54',
    primaryForeground: '#0E0E1A',
    secondary: '#222236',
    secondaryForeground: '#EDE8DF',
    muted: '#222236',
    mutedForeground: '#9494A8',
    accent: '#5B80D4',
    accentForeground: '#FFFFFF',
    destructive: '#D9463E',
    destructiveForeground: '#FFFFFF',
    border: '#2A2A40',
    input: '#2A2A40',
    // Semantic status colours (same in both schemes)
    owned: '#2D9E6B',
    wanted: '#D97832',
    forTrade: '#5B6EE8',
    gold: '#D4AC54',
  },
  radius: 14,
};

export default colors;
