/**
 * Seed data for the PinHunt catalogue.
 *
 * These 20 pins are for local development only. They are inserted via
 *   POST /api/admin/seed-pins  (requires SUPABASE_SERVICE_ROLE_KEY)
 *
 * verificationStatus is 'verified' so they appear in the app immediately.
 * The production catalogue is populated by the import script instead:
 *   pnpm --filter @workspace/scripts run import
 */
import type { CreatePinInput } from './types';

export const SEED_PINS: CreatePinInput[] = [
  // ── Disney Parks ──────────────────────────────────────────────────────────
  {
    pinhuntId: 'PHUK-MOCK-0001',
    title: 'Mickey Classic Silhouette',
    brand: 'Disney Parks',
    collection: 'Classics 2024',
    characters: ['Mickey Mouse'],
    categories: ['Classic'],
    releaseDate: '2024-01-15',
    retailPriceGBP: 14.99,
    estimatedValueGBP: 18,
    origin: 'Walt Disney World',
    edition: 'Open Edition',
    description: 'A timeless gold-backed silhouette pin celebrating the iconic mouse ears. A must-have for any Parks collection.',
    isNewRelease: false,
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0002',
    title: 'Minnie Bow & Polka Dot',
    brand: 'Disney Parks',
    collection: 'Classics 2024',
    characters: ['Minnie Mouse'],
    categories: ['Classic'],
    releaseDate: '2024-01-15',
    retailPriceGBP: 14.99,
    estimatedValueGBP: 16,
    origin: 'Walt Disney World',
    edition: 'Open Edition',
    description: "Minnie's signature pink polka-dot bow rendered in vibrant enamel. A sweet addition to any collector's board.",
    isNewRelease: false,
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0003',
    title: 'Castle Fireworks Night',
    brand: 'Disney Parks',
    collection: 'Park Icons',
    characters: [],
    categories: ['Park Icon', 'Limited Edition'],
    releaseDate: '2023-11-20',
    retailPriceGBP: 17.99,
    limitedEditionSize: 2500,
    estimatedValueGBP: 32,
    origin: 'Disneyland Paris',
    edition: 'LE 2500',
    description: "The park's fairy-tale castle silhouetted against a burst of fireworks. Limited to 2,500 worldwide.",
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0004',
    title: 'Tinker Bell Sparkle Trail',
    brand: 'Disney Parks',
    collection: 'Fairy Tale Friends',
    characters: ['Tinker Bell'],
    categories: ['New Release'],
    releaseDate: '2024-05-01',
    retailPriceGBP: 15.99,
    estimatedValueGBP: 19,
    origin: 'Walt Disney World',
    edition: 'Open Edition',
    description: 'Tink leaves a glittery trail across a teal sky. Perfect for fans of the fairies series.',
    isNewRelease: true,
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0005',
    title: 'Stitch Aloha Hawaiian',
    brand: 'Disney Parks',
    collection: 'Tropical Vibes',
    characters: ['Stitch'],
    categories: ['New Release'],
    releaseDate: '2024-06-01',
    retailPriceGBP: 15.99,
    estimatedValueGBP: 22,
    origin: 'Disneyland Resort',
    edition: 'Open Edition',
    description: "Everyone's favourite blue alien in a tropical shirt. Ohana means family — and this pin means good vibes.",
    isNewRelease: true,
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0006',
    title: 'Dumbo Blue Sky Journey',
    brand: 'Disney Parks',
    collection: 'Park Icons',
    characters: ['Dumbo'],
    categories: ['Park Icon'],
    releaseDate: '2023-09-10',
    retailPriceGBP: 14.99,
    estimatedValueGBP: 14,
    origin: 'Walt Disney World',
    edition: 'Open Edition',
    description: 'The little elephant soaring above white clouds on a soft cerulean background. Classic and charming.',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0007',
    title: 'Haunted Mansion Hitchhikers',
    brand: 'Disney Parks',
    collection: 'Haunted Mansion 50th',
    characters: ['Hitchhiking Ghosts'],
    categories: ['Limited Edition', 'Park Icon'],
    releaseDate: '2023-10-31',
    retailPriceGBP: 19.99,
    limitedEditionSize: 1500,
    estimatedValueGBP: 55,
    origin: 'Walt Disney World',
    edition: 'LE 1500',
    description: 'Three ghostly hitchhikers behind the iconic gothic gate. Part of the exclusive 50th anniversary set.',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0008',
    title: 'Space Mountain Star Blazer',
    brand: 'Disney Parks',
    collection: 'Tomorrowland',
    characters: [],
    categories: ['Limited Edition'],
    releaseDate: '2024-02-14',
    retailPriceGBP: 17.99,
    limitedEditionSize: 3000,
    estimatedValueGBP: 28,
    origin: 'Disneyland Paris',
    edition: 'LE 3000',
    description: 'A gleaming rocket streaking through a starfield. Limited edition from the Tomorrowland series.',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0009',
    title: 'Pirates Treasure Trove',
    brand: 'Disney Parks',
    collection: 'Adventure Seas',
    characters: ['Jack Sparrow'],
    categories: ['Park Icon'],
    releaseDate: '2023-08-01',
    retailPriceGBP: 16.99,
    estimatedValueGBP: 20,
    origin: 'Disneyland Resort',
    edition: 'Open Edition',
    description: 'A skull-and-crossbones chest overflowing with gold doubloons. Yo ho, yo ho!',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0010',
    title: 'Winnie Honey Time',
    brand: 'Disney Parks',
    collection: 'Hundred Acre Friends',
    characters: ['Winnie the Pooh'],
    categories: ['Classic'],
    releaseDate: '2023-07-18',
    retailPriceGBP: 14.99,
    estimatedValueGBP: 15,
    origin: 'Walt Disney World',
    edition: 'Open Edition',
    description: 'Pooh Bear with his beloved honey pot, surrounded by bees and golden drips. Simply delightful.',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  // ── Loungefly ─────────────────────────────────────────────────────────────
  {
    pinhuntId: 'PHUK-MOCK-0011',
    title: 'Wonderland Tea Party',
    brand: 'Loungefly',
    collection: 'Storybook Series Vol. 1',
    characters: ['Alice', 'Mad Hatter'],
    categories: ['Storybook'],
    releaseDate: '2023-12-01',
    retailPriceGBP: 16.99,
    estimatedValueGBP: 21,
    origin: 'Online Exclusive',
    edition: 'Open Edition',
    description: 'Alice and the Mad Hatter share a topsy-turvy tea party scene in rich pastel enamel.',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0012',
    title: "Ariel's Sea Garden",
    brand: 'Loungefly',
    collection: 'Undersea Dreams',
    characters: ['Ariel'],
    categories: ['New Release'],
    releaseDate: '2024-04-01',
    retailPriceGBP: 16.99,
    estimatedValueGBP: 18,
    origin: 'Online Exclusive',
    edition: 'Open Edition',
    description: 'Ariel surrounded by coral and flowing seaweed, rendered in aquamarine and rose gold.',
    isNewRelease: true,
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0013',
    title: "Belle's Library Rose",
    brand: 'Loungefly',
    collection: 'Enchanted Series',
    characters: ['Belle', 'Beast'],
    categories: ['Limited Edition', 'Storybook'],
    releaseDate: '2023-10-01',
    retailPriceGBP: 18.99,
    limitedEditionSize: 2000,
    estimatedValueGBP: 38,
    origin: 'Online Exclusive',
    edition: 'LE 2000',
    description: 'An enchanted rose under glass with the castle library reflected in the dome. 2,000 made.',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0014',
    title: "Aurora's Golden Dream",
    brand: 'Loungefly',
    collection: 'Storybook Series Vol. 1',
    characters: ['Aurora', 'Maleficent'],
    categories: ['Storybook'],
    releaseDate: '2023-12-01',
    retailPriceGBP: 16.99,
    estimatedValueGBP: 22,
    origin: 'Online Exclusive',
    edition: 'Open Edition',
    description: 'Aurora in her golden gown against a swirling purple sky, Maleficent silhouetted in the distance.',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0015',
    title: 'Snow White Apple Garden',
    brand: 'Loungefly',
    collection: 'Storybook Series Vol. 2',
    characters: ['Snow White', 'Evil Queen'],
    categories: ['Storybook'],
    releaseDate: '2024-03-21',
    retailPriceGBP: 16.99,
    estimatedValueGBP: 19,
    origin: 'Online Exclusive',
    edition: 'Open Edition',
    description: 'Snow White in the forest with a gleaming red apple, the Evil Queen lurking behind a gnarled tree.',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  // ── BoxLunch ──────────────────────────────────────────────────────────────
  {
    pinhuntId: 'PHUK-MOCK-0016',
    title: "Simba's Pride Dawn",
    brand: 'BoxLunch',
    collection: 'Circle of Life',
    characters: ['Simba', 'Mufasa'],
    categories: [],
    releaseDate: '2023-08-01',
    retailPriceGBP: 15.99,
    estimatedValueGBP: 20,
    origin: 'BoxLunch Retail',
    edition: 'Open Edition',
    description: 'Young Simba and Mufasa silhouetted against a blazing savannah sunrise.',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0017',
    title: "Aladdin's Magic Journey",
    brand: 'BoxLunch',
    collection: 'Desert Nights',
    characters: ['Aladdin', 'Jasmine', 'Genie'],
    categories: [],
    releaseDate: '2024-01-01',
    retailPriceGBP: 15.99,
    estimatedValueGBP: 17,
    origin: 'BoxLunch Retail',
    edition: 'Open Edition',
    description: 'Aladdin and Jasmine on the magic carpet with Genie trailing behind in a starlit sky.',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0018',
    title: 'Mulan Cherry Blossom',
    brand: 'BoxLunch',
    collection: 'Warriors & Legends',
    characters: ['Mulan', 'Mushu'],
    categories: ['Limited Edition'],
    releaseDate: '2024-03-08',
    retailPriceGBP: 17.99,
    limitedEditionSize: 1800,
    estimatedValueGBP: 34,
    origin: 'BoxLunch Retail',
    edition: 'LE 1800',
    description: "Cherry blossoms frame a red and gold dragon detail. Released on International Women's Day — 1,800 made.",
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0019',
    title: 'Moana Wave Rider',
    brand: 'BoxLunch',
    collection: 'Ocean Explorers',
    characters: ['Moana', 'Maui'],
    categories: [],
    releaseDate: '2023-10-01',
    retailPriceGBP: 15.99,
    estimatedValueGBP: 19,
    origin: 'BoxLunch Retail',
    edition: 'Open Edition',
    description: 'A curling ocean wave in turquoise and white, with a stylised fishhook motif. The sea calls.',
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
  {
    pinhuntId: 'PHUK-MOCK-0020',
    title: 'Raya Dragon Heart',
    brand: 'BoxLunch',
    collection: 'Warriors & Legends',
    characters: ['Raya', 'Sisu'],
    categories: ['Limited Edition', 'New Release'],
    releaseDate: '2024-07-10',
    retailPriceGBP: 17.99,
    limitedEditionSize: 2200,
    estimatedValueGBP: 29,
    origin: 'BoxLunch Retail',
    edition: 'LE 2200',
    description: 'A luminous dragon gem in deep teal and violet with gold filigree. Just 2,200 made.',
    isNewRelease: true,
    verificationStatus: 'verified',
    catalogueSource: 'pinhunt_seed',
  },
];
