/**
 * Seed data for the PinHunt catalogue.
 *
 * These are the 20 initial pins. IDs are stable PinHunt internal IDs.
 * imageUrl is intentionally omitted — add real photos via the pin management
 * screen once object storage is wired up.
 *
 * Run via: POST /api/admin/seed-pins  (development only)
 */
import type { CreatePinInput } from './types';

export const SEED_PINS: CreatePinInput[] = [
  // ── Disney Parks ──────────────────────────────────────────────────────────
  {
    id: 'dp-001',
    title: 'Mickey Classic Silhouette',
    brand: 'Disney Parks',
    collection: 'Classics 2024',
    characters: ['Mickey Mouse'],
    releaseDate: '2024-01-15',
    retailPriceGBP: 14.99,
    estimatedValueGBP: 18,
    origin: 'Walt Disney World',
    edition: 'Open Edition',
    description: 'A timeless gold-backed silhouette pin celebrating the iconic mouse ears. A must-have for any Parks collection.',
    isNewRelease: false,
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'dp-002',
    title: 'Minnie Bow & Polka Dot',
    brand: 'Disney Parks',
    collection: 'Classics 2024',
    characters: ['Minnie Mouse'],
    releaseDate: '2024-01-15',
    retailPriceGBP: 14.99,
    estimatedValueGBP: 16,
    origin: 'Walt Disney World',
    edition: 'Open Edition',
    description: "Minnie's signature pink polka-dot bow rendered in vibrant enamel. A sweet addition to any collector's board.",
    isNewRelease: false,
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'dp-003',
    title: 'Castle Fireworks Night',
    brand: 'Disney Parks',
    collection: 'Park Icons',
    characters: [],
    releaseDate: '2023-11-20',
    retailPriceGBP: 17.99,
    limitedEditionSize: 2500,
    estimatedValueGBP: 32,
    origin: 'Disneyland Paris',
    edition: 'LE 2500',
    description: "The park's fairy-tale castle silhouetted against a burst of fireworks. Limited to 2,500 worldwide.",
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'dp-004',
    title: 'Tinker Bell Sparkle Trail',
    brand: 'Disney Parks',
    collection: 'Fairy Tale Friends',
    characters: ['Tinker Bell'],
    releaseDate: '2024-05-01',
    retailPriceGBP: 15.99,
    estimatedValueGBP: 19,
    origin: 'Walt Disney World',
    edition: 'Open Edition',
    description: 'Tink leaves a glittery trail across a teal sky. Perfect for fans of the fairies series.',
    isNewRelease: true,
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'dp-005',
    title: 'Stitch Aloha Hawaiian',
    brand: 'Disney Parks',
    collection: 'Tropical Vibes',
    characters: ['Stitch'],
    releaseDate: '2024-06-01',
    retailPriceGBP: 15.99,
    estimatedValueGBP: 22,
    origin: 'Disneyland Resort',
    edition: 'Open Edition',
    description: "Everyone's favourite blue alien in a tropical shirt. Ohana means family — and this pin means good vibes.",
    isNewRelease: true,
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'dp-006',
    title: 'Dumbo Blue Sky Journey',
    brand: 'Disney Parks',
    collection: 'Park Icons',
    characters: ['Dumbo'],
    releaseDate: '2023-09-10',
    retailPriceGBP: 14.99,
    estimatedValueGBP: 14,
    origin: 'Walt Disney World',
    edition: 'Open Edition',
    description: 'The little elephant soaring above white clouds on a soft cerulean background. Classic and charming.',
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'dp-007',
    title: 'Haunted Mansion Hitchhikers',
    brand: 'Disney Parks',
    collection: 'Haunted Mansion 50th',
    characters: ['Hitchhiking Ghosts'],
    releaseDate: '2023-10-31',
    retailPriceGBP: 19.99,
    limitedEditionSize: 1500,
    estimatedValueGBP: 55,
    origin: 'Walt Disney World',
    edition: 'LE 1500',
    description: 'Three ghostly hitchhikers behind the iconic gothic gate. Part of the exclusive 50th anniversary set.',
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'dp-008',
    title: 'Space Mountain Star Blazer',
    brand: 'Disney Parks',
    collection: 'Tomorrowland',
    characters: [],
    releaseDate: '2024-02-14',
    retailPriceGBP: 17.99,
    limitedEditionSize: 3000,
    estimatedValueGBP: 28,
    origin: 'Disneyland Paris',
    edition: 'LE 3000',
    description: 'A gleaming rocket streaking through a starfield. Limited edition from the Tomorrowland series.',
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'dp-009',
    title: 'Pirates Treasure Trove',
    brand: 'Disney Parks',
    collection: 'Adventure Seas',
    characters: ['Jack Sparrow'],
    releaseDate: '2023-08-01',
    retailPriceGBP: 16.99,
    estimatedValueGBP: 20,
    origin: 'Disneyland Resort',
    edition: 'Open Edition',
    description: 'A skull-and-crossbones chest overflowing with gold doubloons. Yo ho, yo ho!',
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'dp-010',
    title: 'Winnie Honey Time',
    brand: 'Disney Parks',
    collection: 'Hundred Acre Friends',
    characters: ['Winnie the Pooh'],
    releaseDate: '2023-07-18',
    retailPriceGBP: 14.99,
    estimatedValueGBP: 15,
    origin: 'Walt Disney World',
    edition: 'Open Edition',
    description: 'Pooh Bear with his beloved honey pot, surrounded by bees and golden drips. Simply delightful.',
    catalogueSource: 'pinhunt_seed',
  },
  // ── Loungefly ────────────────────────────────────────────────────────────
  {
    id: 'lf-001',
    title: 'Wonderland Tea Party',
    brand: 'Loungefly',
    collection: 'Storybook Series Vol. 1',
    characters: ['Alice', 'Mad Hatter'],
    releaseDate: '2023-12-01',
    retailPriceGBP: 16.99,
    estimatedValueGBP: 21,
    origin: 'Online Exclusive',
    edition: 'Open Edition',
    description: 'Alice and the Mad Hatter share a topsy-turvy tea party scene in rich pastel enamel.',
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'lf-002',
    title: "Ariel's Sea Garden",
    brand: 'Loungefly',
    collection: 'Undersea Dreams',
    characters: ['Ariel'],
    releaseDate: '2024-04-01',
    retailPriceGBP: 16.99,
    estimatedValueGBP: 18,
    origin: 'Online Exclusive',
    edition: 'Open Edition',
    description: 'Ariel surrounded by coral and flowing seaweed, rendered in aquamarine and rose gold.',
    isNewRelease: true,
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'lf-003',
    title: "Belle's Library Rose",
    brand: 'Loungefly',
    collection: 'Enchanted Series',
    characters: ['Belle', 'Beast'],
    releaseDate: '2023-10-01',
    retailPriceGBP: 18.99,
    limitedEditionSize: 2000,
    estimatedValueGBP: 38,
    origin: 'Online Exclusive',
    edition: 'LE 2000',
    description: 'An enchanted rose under glass with the castle library reflected in the dome. 2,000 made.',
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'lf-004',
    title: "Aurora's Golden Dream",
    brand: 'Loungefly',
    collection: 'Storybook Series Vol. 1',
    characters: ['Aurora', 'Maleficent'],
    releaseDate: '2023-12-01',
    retailPriceGBP: 16.99,
    estimatedValueGBP: 22,
    origin: 'Online Exclusive',
    edition: 'Open Edition',
    description: 'Aurora in her golden gown against a swirling purple sky, Maleficent silhouetted in the distance.',
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'lf-005',
    title: 'Snow White Apple Garden',
    brand: 'Loungefly',
    collection: 'Storybook Series Vol. 2',
    characters: ['Snow White', 'Evil Queen'],
    releaseDate: '2024-03-21',
    retailPriceGBP: 16.99,
    estimatedValueGBP: 19,
    origin: 'Online Exclusive',
    edition: 'Open Edition',
    description: 'Snow White in the forest with a gleaming red apple, the Evil Queen lurking behind a gnarled tree.',
    catalogueSource: 'pinhunt_seed',
  },
  // ── BoxLunch ─────────────────────────────────────────────────────────────
  {
    id: 'bl-001',
    title: "Simba's Pride Dawn",
    brand: 'BoxLunch',
    collection: 'Circle of Life',
    characters: ['Simba', 'Mufasa'],
    releaseDate: '2023-08-01',
    retailPriceGBP: 15.99,
    estimatedValueGBP: 20,
    origin: 'BoxLunch Retail',
    edition: 'Open Edition',
    description: 'Young Simba and Mufasa silhouetted against a blazing savannah sunrise.',
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'bl-002',
    title: "Aladdin's Magic Journey",
    brand: 'BoxLunch',
    collection: 'Desert Nights',
    characters: ['Aladdin', 'Jasmine', 'Genie'],
    releaseDate: '2024-01-01',
    retailPriceGBP: 15.99,
    estimatedValueGBP: 17,
    origin: 'BoxLunch Retail',
    edition: 'Open Edition',
    description: 'Aladdin and Jasmine on the magic carpet with Genie trailing behind in a starlit sky.',
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'bl-003',
    title: 'Mulan Cherry Blossom',
    brand: 'BoxLunch',
    collection: 'Warriors & Legends',
    characters: ['Mulan', 'Mushu'],
    releaseDate: '2024-03-08',
    retailPriceGBP: 17.99,
    limitedEditionSize: 1800,
    estimatedValueGBP: 34,
    origin: 'BoxLunch Retail',
    edition: 'LE 1800',
    description: "Cherry blossoms frame a red and gold dragon detail. Released on International Women's Day — 1,800 made.",
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'bl-004',
    title: 'Moana Wave Rider',
    brand: 'BoxLunch',
    collection: 'Ocean Explorers',
    characters: ['Moana', 'Maui'],
    releaseDate: '2023-10-01',
    retailPriceGBP: 15.99,
    estimatedValueGBP: 19,
    origin: 'BoxLunch Retail',
    edition: 'Open Edition',
    description: 'A curling ocean wave in turquoise and white, with a stylised fishhook motif. The sea calls.',
    catalogueSource: 'pinhunt_seed',
  },
  {
    id: 'bl-005',
    title: 'Raya Dragon Heart',
    brand: 'BoxLunch',
    collection: 'Warriors & Legends',
    characters: ['Raya', 'Sisu'],
    releaseDate: '2024-07-10',
    retailPriceGBP: 17.99,
    limitedEditionSize: 2200,
    estimatedValueGBP: 29,
    origin: 'BoxLunch Retail',
    edition: 'LE 2200',
    description: 'A luminous dragon gem in deep teal and violet with gold filigree. Just 2,200 made.',
    isNewRelease: true,
    catalogueSource: 'pinhunt_seed',
  },
];
