// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/collection-page/Current.tsx": () => import("../components/mockups/collection-page/Current.tsx"),
  "./components/mockups/collection-page/Gallery.tsx": () => import("../components/mockups/collection-page/Gallery.tsx"),
  "./components/mockups/collection-page/QuestProgress.tsx": () => import("../components/mockups/collection-page/QuestProgress.tsx"),
  "./components/mockups/collection-page/TrophyCase.tsx": () => import("../components/mockups/collection-page/TrophyCase.tsx"),
  "./components/mockups/pinhunt-style/CabinetStyle.tsx": () => import("../components/mockups/pinhunt-style/CabinetStyle.tsx"),
  "./components/mockups/pinhunt-style/ElectricStyle.tsx": () => import("../components/mockups/pinhunt-style/ElectricStyle.tsx"),
  "./components/mockups/pinhunt-style/GoldenStyle.tsx": () => import("../components/mockups/pinhunt-style/GoldenStyle.tsx")
};
